### ISSUE TITLE
Widget not exported in PDF (Windows/Linux)

### ISSUE THREAD

**Issue by obook** [obook/TeX2Board#2]
PDF exported do not content any Web widget, just black or white frame, with QTWebWidget Error. TeX2Board also.

**Comment by letsfindaway** [comment]
I think you have seen my PR in OpenBoard and my comment on your issue there. As a workaround: is it an option to place the generated and rendered LaTeX output as image on the board using [windows.sankore.addObject](https://github.com/letsfindaway/OpenBoard/wiki/Widget-API#windowsankoreaddobjecturlwidthheightxyisbackground)? I'm not a JavaScript expert, so this might be a stupid idea.

The TeX2Board widget including the Internet connectivity would then only be needed to create this image. After that, everything works offline - and PDF export would work, too.

**Comment by obook** [comment]
The bug in OpenBoard is fixed in  OpenBoard V1.7.0 release. See https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.7.0. You can export LaTeX forumula in PDF documents.
