### ISSUE TITLE
Update id in config.xml

### ISSUE THREAD

**Issue by letsfindaway** [obook/TeX2Board#3]
Hi Olivier,

I discovered this project when looking for the issue you reported in OpenBoard. I'm not part of the OpenBoard project, but probably currently the main contributor, especially for the upcoming 1.7 release, which is expected somewhere next year. Here we replace the `QWebKit` based browser engine with `QWebEngine`, which in turn is based on Chrome. This will also affect the widgets.

For this issue I want to point you to a small improvement: Please choose a **unique** id for your widget. So it is better to use `id="http://obooklage.free.fr/TeX2Book"`, as this will uniquely identify your widget.

This very much helps the automatic upgrade of widgets when moving from 1.6.x to 1.7.x. Here OpenBoard has to know which widgets are in a document. The id is more or less the only way to find this out.

For the future widget API, please also have a look at https://github.com/letsfindaway/OpenBoard/wiki/Widget-API. The main difference is that functions returning a value will be asynchronous. A prominent example is `window.sankore.preference`. See https://github.com/letsfindaway/OpenBoard/wiki/Widget-API#functions on examples how this works with the asynchronous API.

In OpenBoard 1.7 you will have the option to "Fix" a widget. This takes a snapshot of the current state and shows this instead of the actual web page. Using this function also allows to export this snapshot to PDF. See also some thoughts on related things here: https://github.com/letsfindaway/OpenBoard/issues/98.

Martin

**Comment by obook** [comment]
> Hi Olivier,
> 
> I discovered this project when looking for the issue you reported in OpenBoard. I'm not part of the OpenBoard project, but probably currently the main contributor, especially for the upcoming 1.7 release, which is expected somewhere next year. Here we replace the `QWebKit` based browser engine with `QWebEngine`, which in turn is based on Chrome. This will also affect the widgets.
> 
> For this issue I want to point you to a small improvement: Please choose a **unique** id for your widget. So it is better to use `id="http://obooklage.free.fr/TeX2Book"`, as this will uniquely identify your widget.
> 
> This very much helps the automatic upgrade of widgets when moving from 1.6.x to 1.7.x. Here OpenBoard has to know which widgets are in a document. The id is more or less the only way to find this out.
> 
> For the future widget API, please also have a look at https://github.com/letsfindaway/OpenBoard/wiki/Widget-API. The main difference is that functions returning a value will be asynchronous. A prominent example is `window.sankore.preference`. See https://github.com/letsfindaway/OpenBoard/wiki/Widget-API#functions on examples how this works with the asynchronous API.
> 
> In OpenBoard 1.7 you will have the option to "Fix" a widget. This takes a snapshot of the current state and shows this instead of the actual web page. Using this function also allows to export this snapshot to PDF. See also some thoughts on related things here: [letsfindaway/OpenBoard#98](https://github.com/letsfindaway/OpenBoard/issues/98).
> 
> Martin

Hello Martin.
Is done today, this widget is now compatible with OpenBoard >= 1.7.0

Regards,
Olivier.
