### ISSUE TITLE
Custom widget installation directory

### ISSUE THREAD

**Issue by letsfindaway** [obook/TeX2Board#4]
In `README.md` you propose to install the widget to the program installation folders. It is not well documented, but OpenBoard also provides a custom widget installation folder in the user directory. The default paths are:

- Linux: `~/.local/share/OpenBoard/interactive content/`
- Windows (hopefully, cannot check): `C:/Users/<USER>/AppData/Local/OpenBoard/interactive content/`

The recommended way is to install custom widgets to these folders.

**Comment by obook** [comment]
Nice information. Tested successfully under Linux,
Thank you.

**Comment by obook** [comment]
Tested successfully under Windows,
